(function(g){var window=this;var k4=function(a,b,c){var d=b.oa();g.M(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.yc(c?c:"mqdefault.jpg");var f=b instanceof g.lB&&b.lengthSeconds?g.XQ(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.nE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.lB?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.cj||g.EN("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Ej(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.pE&&(d.playlist_length=b.getLength());a.update(d)},l4=function(a,b){g.eD.call(this,{C:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},m4=function(a){g.W.call(this,{C:"div",
W:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{C:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{C:"span",G:"ytp-upnext-top",J:[{C:"span",G:"ytp-upnext-header",U:"Up Next"},{C:"span",G:"ytp-upnext-title",U:"{{title}}"},{C:"span",G:"ytp-upnext-author",U:"{{author}}"}]},{C:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{C:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{C:"circle",
G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{C:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{C:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{C:"span",G:"ytp-upnext-bottom",J:[{C:"span",G:"ytp-upnext-cancel"},{C:"span",G:"ytp-upnext-paused",U:"Autoplay is paused"}]}]});
this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.W({C:"button",W:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},U:"Cancel"});g.I(this,this.A);this.A.da("click",this.WH,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.B=this.o=this.u=null;this.F=new g.N(this.Ml,5E3,this);g.I(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.LJ);this.ry();this.K(a,"autonavvisibility",this.ry);this.K(a,"mdxnowautoplaying",
this.aJ);this.K(a,"mdxautoplaycanceled",this.bJ);this.K(a,"mdxautoplayupnext",this.OA);3==this.l.getPresentingPlayerType()&&(a=(a=g.sK(g.mK(this.l)))?a.XC():null)&&this.OA(a)},n4=function(a,b){if(!a.o){g.iq("a11y-announce","Up Next "+a.u.title);
a.H=g.P();a.o=new g.N((0,g.y)(a.Fo,a,b),25);a.Fo(b);var c=b||g.S(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.ma("onAutonavCoundownStarted",c)}g.ko(a.element,"ytp-upnext-autoplay-paused")},p4=function(a){o4(a);
a.H=g.P();a.Fo();g.L(a.element,"ytp-upnext-autoplay-paused")},o4=function(a){a.o&&(a.o.dispose(),a.o=null)},q4=function(a,b){b=void 0===b?!1:b;
if(g.R(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.oa(),a.Ml(),a.B=new Notification("Up Next",{body:c.title,icon:c.yc()}),a.D=a.K(a.B,"click",a.DJ),a.F.start())}o4(a);a.l.nextVideo(!1,b)},r4=function(a){l4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({C:"div",G:"ytp-subscribe-card",J:[{C:"img",G:"ytp-author-image",L:{src:b.Nd}},{C:"div",G:"ytp-subscribe-card-right",J:[{C:"div",G:"ytp-author-name",U:b.author},{C:"div",G:"html5-subscribe-button-container"}]}]});g.I(this,this.l);this.l.g(this.element);this.o=new g.hW("Subscribe",null,"Unsubscribe",null,!0,!1,b.Qf,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},s4=function(a){var b=
g.X(a),c=g.ex||g.Ch?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{C:"a",W:e,L:{href:"{{url}}",target:d?b.u:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{C:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{C:"span",G:"ytp-videowall-still-info",J:[{C:"span",G:"ytp-videowall-still-info-bg",J:[{C:"span",G:"ytp-videowall-still-info-content",L:c,J:[{C:"span",G:"ytp-videowall-still-info-title",U:"{{title}}"},{C:"span",G:"ytp-videowall-still-info-author",
U:"{{author_and_views}}"},{C:"span",G:"ytp-videowall-still-info-live",U:"Live"},{C:"span",G:"ytp-videowall-still-info-duration",U:"{{duration}}"}]}]}]},{C:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{C:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{C:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{C:"span",U:"{{playlist_length}}"},")"]}]},{C:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:[{C:"span",G:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{C:"span",G:"ytp-videowall-still-listlabel-length",U:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.Ls(this);g.I(this,this.u);this.da("click",this.D);this.da("keypress",this.F);this.u.K(a,"videodatachange",this.B);g.X(a).F&&g.sO(a.app.O,this.element,this);this.B()},t4=function(a){g.JK(a.l,a.element);
var b=a.o.oa().videoId,c=a.o.getPlaylistId();g.nY(a.l.app,b,a.o.bd,c,void 0,void 0,void 0)},u4=function(a){l4.call(this,a,"videowall-endscreen");
this.H=a;this.B=0;this.o=[];this.D=this.u=this.A=null;this.F=this.R=!1;this.O=null;this.ba=new g.Ls(this);g.I(this,this.ba);this.I=new g.N(g.Qa(g.L,this.element,"ytp-show-tiles"),0);g.I(this,this.I);var b=new g.W({C:"button",W:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},J:[g.IP()]});g.I(this,b);b.g(this.element);b.da("click",this.wF,this);this.M=new g.$C({C:"div",G:"ytp-endscreen-content"});g.I(this,this.M);this.M.g(this.element);b=new g.W({C:"button",W:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Next"},J:[g.JP()]});g.I(this,b);b.g(this.element);b.da("click",this.vF,this);this.l=new m4(a);g.I(this,this.l);g.GK(this.player,this.l.element,4);this.hide()},v4=function(a){return g.HK(a.player)&&a.lu()&&!a.D},w4=function(a,b){return(0,g.G)(b.suggestions,function(c){c=g.lS(g.X(a.H),c);
g.I(a,c);return c})},x4=function(a){var b=a.Ne();
b!=a.R&&(a.R=b,a.player.N("autonavvisibility"))},z4=function(a){g.UK.call(this,a);
this.g=null;this.i=new g.Ls(this);g.I(this,this.i);this.l=g.X(a);y4(a)?this.g=new u4(this.player):this.l.Ga?this.g=new r4(this.player):this.g=new l4(this.player);g.I(this,this.g);g.GK(this.player,this.g.element,4);this.Nz();this.i.K(a,"videodatachange",this.Nz,this);this.i.K(a,g.mE("endscreen"),this.ME,this);this.i.K(a,"crx_endscreen",this.NE,this)},y4=function(a){a=g.X(a);
return a.Ba&&!a.Ga};
g.t(l4,g.eD);l4.prototype.create=function(){this.created=!0};
l4.prototype.destroy=function(){this.created=!1};
l4.prototype.lu=function(){return!1};
l4.prototype.Ne=function(){return!1};g.t(m4,g.W);g.h=m4.prototype;g.h.Ml=function(){this.B&&(this.F.stop(),this.Ma(this.D),this.D=null,this.B.close(),this.B=null)};
g.h.ry=function(){g.dD(this,this.l.Ne())};
g.h.DJ=function(){window.focus();this.Ml()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Fo=function(a){a=a||g.S(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.P()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?q4(this,!0):this.o&&this.o.start()};
g.h.LJ=function(a){!g.$d(this.A.element,g.es(a))&&g.oS(a,this.l)&&q4(this)};
g.h.WH=function(){g.oK(this.l,!0)};
g.h.aJ=function(a){this.l.getPresentingPlayerType();this.show();n4(this,a)};
g.h.OA=function(a){this.l.getPresentingPlayerType();this.u&&this.u.oa().videoId==a.oa().videoId||(this.u=a,k4(this,a,"hqdefault.jpg"))};
g.h.bJ=function(){this.l.getPresentingPlayerType();o4(this);this.hide()};
g.h.T=function(){o4(this);this.Ml();g.W.prototype.T.call(this)};g.t(r4,l4);g.t(s4,g.W);s4.prototype.D=function(a){g.oS(a,this.l,this.A,this.o.bd||void 0)&&t4(this)};
s4.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.js(a)||(t4(this),g.is(a))}};
s4.prototype.B=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.A=a.Nb?!1:b.i};g.t(u4,l4);g.h=u4.prototype;g.h.create=function(){l4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=w4(this,a),this.u=a);this.If();this.ba.K(this.player,"appresize",this.If);this.ba.K(this.player,"onVideoAreaChange",this.If);this.ba.K(this.player,"videodatachange",this.xF);this.ba.K(this.player,"autonavchange",this.Qq);this.ba.K(this.player,"autonavcancel",this.uF);a=this.u.autonavState;a!=this.O&&this.Qq(a);this.ba.K(this.element,"transitionend",this.bL)};
g.h.destroy=function(){g.Ns(this.ba);g.pf(this.o);this.o=[];this.A=null;l4.prototype.destroy.call(this);g.ko(this.element,"ytp-show-tiles");this.I.stop();this.O=this.u.autonavState};
g.h.lu=function(){return 1!=this.u.autonavState};
g.h.show=function(){l4.prototype.show.call(this);g.ko(this.element,"ytp-show-tiles");g.X(this.player).g?g.yo(this.I):this.I.start();(this.F||this.D&&this.D!=this.u.clientPlaybackNonce)&&g.oK(this.player,!1);v4(this)?(x4(this),2==this.u.autonavState?g.R(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?q4(this.l,!0):n4(this.l):3==this.u.autonavState&&p4(this.l)):(g.oK(this.player,!0),x4(this))};
g.h.hide=function(){l4.prototype.hide.call(this);p4(this.l);x4(this)};
g.h.bL=function(a){g.es(a)==this.element&&this.If()};
g.h.If=function(){if(this.A&&this.A.length){g.L(this.element,"ytp-endscreen-paginate");var a=g.xK(this.H,!0),b=g.tD(this.H);b&&(b=b.Ac()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,u=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=r*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.od(a.width/m||1,1,1.21);n*=g.od(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Rh(a,m,n);g.zh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.u=f;k4(c,f,"hqdefault.jpg");g.M(this.element,"ytp-endscreen-takeover",v4(this));x4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.pd(p+this.B,l),0!=r){u=this.o[c];u||(u=new s4(this.player),this.o[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),E=Math.floor(n*(k+r)/e)-z-4,F=Math.floor(m*(f+r)/b)-C-4;g.Hh(u.element,C,z);g.Rh(u.element,F,E);g.zh(u.element,"transitionDelay",(k+f)/20+"s");g.M(u.element,"ytp-videowall-still-mini",1==r);g.M(u.element,"ytp-videowall-still-large",2<r);r=u;p=this.A[p];r.o!=p&&(r.o=p,k4(r,p,g.io(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.bd)&&p.itct)&&(u=r.l,g.X(u).F&&g.tO(u.app.O,r.element,p));c++}g.M(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Wd(e.element),g.of(e);this.o.length=c}};
g.h.xF=function(){var a=this.player.getVideoData();this.u!=a&&(this.B=0,this.A=w4(this,a),this.u=a,this.If())};
g.h.vF=function(){this.B+=this.o.length;this.If()};
g.h.wF=function(){this.B-=this.o.length;this.If()};
g.h.ZD=function(){return!!this.l.o};
g.h.Qq=function(a){1==a?(this.F=!1,this.D=this.u.clientPlaybackNonce,o4(this.l),this.Fa()&&this.If()):(this.F=!0,this.Fa()&&v4(this)&&(2==a?n4(this.l):3==a&&p4(this.l)))};
g.h.uF=function(a){if(a){for(a=0;a<this.o.length;a++)g.KK(this.H,this.o[a].element,!0);this.Qq(1)}else this.D=null,this.F=!1;this.If()};
g.h.Ne=function(){return this.Fa()&&v4(this)};g.t(z4,g.UK);g.h=z4.prototype;g.h.Kk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!y4(this.player)||b;a=a.Lc;var c=g.OX(this.player.app);return b&&!a&&!c};
g.h.Ne=function(){return this.g.Ne()};
g.h.VD=function(){return this.Ne()?this.g.ZD():!1};
g.h.T=function(){g.CK(this.player,"endscreen");g.UK.prototype.T.call(this)};
g.h.load=function(){g.UK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.UK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.ME=function(a){this.Kk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.NE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Nz=function(){g.CK(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.jE(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.I(this,a);var b=new g.jE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.I(this,b);g.zK(this.player,[a,b])};g.pV.endscreen=z4;})(_yt_player);
